import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import AuthModel from "@/components/shared/authModel";
import getCurrentUser from "./api/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Authentication App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Navbar currentUser={currentUser?.id} />
        <AuthModel currentUser={currentUser?.id} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
